# Generated by Django 6.1 on 2026-09-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('tami', "Ta'mi yoqmadi"), ('buzilgan', 'Mahsulot buzilgan/sifatsiz yetib keldi'), ('notogri', "Noto'g'ri mahsulot yuborildi"), ('muddati', "Muddati o'tgan"), ('boshqa', 'Boshqa sabab')], max_length=20, verbose_name='Sabab')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='refunds/', verbose_name='Dalil rasm')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='kutilmoqda', max_length=20, verbose_name='Status')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Qaytarilgan summa')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name="So'rov sanasi")),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='orders.order', verbose_name='Buyurtma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Qaytarish so'rovi",
                'verbose_name_plural': "Qaytarish so'rovlari",
                'ordering': ['-requested_at'],
            },
        ),
    ]
