# Generated by Django 6.1 on 2026-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Kod')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Tavsif')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Chegirma (%)')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal ishlatilish soni')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
                ('active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo-kod',
                'verbose_name_plural': 'Promo-kodlar',
            },
        ),
    ]
