# Generated by Django 6.1 on 2026-09-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10, verbose_name='Provayder')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Summa (so'm)")),
                ('state', models.CharField(choices=[('created', 'Yaratildi (kutilmoqda)'), ('performed', "To'landi"), ('cancelled', 'Bekor qilindi')], default='created', max_length=12, verbose_name='Holati')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=64, verbose_name='Provayder tranzaksiya ID')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='Xato sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
