# Generated by Django 6.1 on 2026-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Lavozim')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name="Bo'lim")),
                ('location', models.CharField(default='Toshkent', max_length=150, verbose_name='Joylashuv')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Bo'sh ish o'rni",
                'verbose_name_plural': "Bo'sh ish o'rinlari",
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon')),
                ('working_hours', models.CharField(default='09:00 – 22:00', max_length=100, verbose_name='Ish vaqti')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
