# Generated by Django 6.1 on 2026-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_loyalty_points_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tiklash kodi (hash)'),
        ),
    ]
