# Generated by Django 6.1 on 2026-09-23 04:40

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    from accounts.models import generate_referral_code
    seen = set()
    for user in User.objects.all():
        code = generate_referral_code()
        while code in seen or User.objects.filter(referral_code=code).exists():
            code = generate_referral_code()
        seen.add(code)
        user.referral_code = code
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_recovery_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus_awarded',
            field=models.BooleanField(default=False, verbose_name='Referral bonusi berildi'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='', max_length=8, verbose_name='Referral kodi'),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referral_code, max_length=8, unique=True, verbose_name='Referral kodi'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Kim taklif qilgan'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code',
            field=models.CharField(blank=True, default=accounts.models.generate_telegram_link_code, max_length=8, verbose_name='Telegram ulash kodi'),
        ),
    ]
