# Generated by Django 6.1 on 2026-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon SMS orqali tasdiqlangan'),
        ),
    ]
