# Generated by Django 6.1 on 2026-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_composition_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (en)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_en',
            field=models.TextField(blank=True, verbose_name='Tarkibi (en)'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_ru',
            field=models.TextField(blank=True, verbose_name='Tarkibi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (en)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (en)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi (uz)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text="Masalan: un, shakar, tuxum, sariyog', vanil", verbose_name='Tarkibi (uz)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif (uz)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nomi (uz)'),
        ),
    ]
