# Generated by Django 6.1 on 2026-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=20, verbose_name='Zaxira miqdori'),
        ),
    ]
