# Generated by Django 6.1 on 2026-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kaloriya (kkal, 100gr)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Uglevod (gr, 100gr)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Yog' (gr, 100gr)"),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Oqsil (gr, 100gr)'),
        ),
    ]
