# Generated by Django 6.1 on 2026-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_calories_product_carbs_g_product_fat_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, help_text='Masalan: 1.5 kg, 6 dona, 500 ml', max_length=50, verbose_name="Miqdori/og'irligi (uz)"),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_en',
            field=models.CharField(blank=True, max_length=50, verbose_name="Miqdori/og'irligi (en)"),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name="Miqdori/og'irligi (ru)"),
        ),
    ]
