# Generated by Django 6.1 on 2026-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_quantity_product_quantity_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text="Kompyuterdan rasm yuklang. Bo'sh qoldirilsa, yuqoridagi URL ishlatiladi.", null=True, upload_to='products/', verbose_name='Rasm (yuklash)'),
        ),
    ]
