# Generated by Django 6.1 on 2026-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_inscription',
            field=models.BooleanField(default=False, help_text='Mijoz tort ustiga yoziladigan matnni kiritishi mumkin.', verbose_name='Yozuv yozish mumkin'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by_weight',
            field=models.BooleanField(default=False, help_text="Belgilansa, narx 1 kg uchun hisoblanadi va mijoz og'irlikni (1–3 kg) o'zi tanlaydi.", verbose_name="Og'irlik bo'yicha sotiladi"),
        ),
    ]
