# Generated by Django 6.1 on 2026-09-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Yetkazib berish manzili')),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Karta (Payme/Click)')], default='naqd', max_length=10, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tasdiqlangan', 'Tasdiqlangan'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yetkazilmoqda', 'Yetkazilmoqda'), ('yetkazildi', 'Yetkazildi'), ('qaytarildi', 'Qaytarildi'), ('bekor', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Umumiy summa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('emoji', models.CharField(default='🍰', max_length=8, verbose_name='Emoji')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narx')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
