# Generated by Django 6.1 on 2026-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='emoji',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Rasm manzili'),
        ),
    ]
