# Generated by Django 6.1 on 2026-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_emoji_orderitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kuryer ismi'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Kuryer telefoni'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taxminiy yetkazish vaqti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Karta (Payme/Click)'), ('wallet', 'Wallet balansidan')], default='naqd', max_length=10, verbose_name="To'lov usuli"),
        ),
    ]
