# Generated by Django 6.1 on 2026-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Berilgan ballar'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan ballar'),
        ),
    ]
