# Generated by Django 6.1 on 2026-09-23 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_latitude_order_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yetkazish sanasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Yetkazish narxi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, choices=[('10-12', '10:00 – 12:00'), ('12-14', '12:00 – 14:00'), ('14-16', '14:00 – 16:00'), ('16-18', '16:00 – 18:00'), ('18-20', '18:00 – 20:00'), ('20-22', '20:00 – 22:00')], max_length=5, verbose_name='Yetkazish vaqti'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inscription',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tortdagi yozuv'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Og'irligi (kg)"),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.OneToOneField(blank=True, help_text='Kuryer panelga kirishi uchun uning saytdagi hisobini tanlang.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Hisob')),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.courier', verbose_name='Kuryer'),
        ),
    ]
